/**
 * Emoji shortcode map for :emoji: typeahead support.
 * Maps shortcode names to emoji characters.
 */
export const EMOJI_MAP: Record<string, string> = {
  // Faces - smiling
  smile: '😊',
  grin: '😀',
  grinning: '😁',
  joy: '😂',
  rofl: '🤣',
  blush: '😊',
  innocent: '😇',
  wink: '😉',
  relaxed: '☺️',
  yum: '😋',
  heart_eyes: '😍',
  kissing_heart: '😘',
  kissing: '😗',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  stuck_out_tongue_closed_eyes: '😝',
  sunglasses: '😎',
  smirk: '😏',

  // Faces - neutral/skeptical
  thinking: '🤔',
  raised_eyebrow: '🤨',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  rolling_eyes: '🙄',
  hushed: '😯',
  open_mouth: '😮',
  astonished: '😲',

  // Faces - negative
  worried: '😟',
  frowning: '😦',
  anguished: '😧',
  fearful: '😨',
  cry: '😢',
  sob: '😭',
  scream: '😱',
  confounded: '😖',
  persevere: '😣',
  disappointed: '😞',
  sweat: '😓',
  tired_face: '😫',
  sleepy: '😪',
  sleeping: '😴',
  angry: '😠',
  rage: '😡',
  triumph: '😤',
  pensive: '😔',
  confused: '😕',

  // Faces - sick/costume
  mask: '😷',
  thermometer_face: '🤒',
  bandage_face: '🤕',
  nauseated_face: '🤢',
  sneezing_face: '🤧',
  hot_face: '🥵',
  cold_face: '🥶',
  woozy_face: '🥴',
  dizzy_face: '😵',
  exploding_head: '🤯',

  // Hands/gestures
  thumbsup: '👍',
  '+1': '👍',
  thumbsdown: '👎',
  '-1': '👎',
  clap: '👏',
  raised_hands: '🙌',
  open_hands: '👐',
  palms_up: '🤲',
  handshake: '🤝',
  pray: '🙏',
  wave: '👋',
  call_me: '🤙',
  muscle: '💪',
  fist: '✊',
  punch: '👊',
  ok_hand: '👌',
  pinching_hand: '🤏',
  v: '✌️',
  crossed_fingers: '🤞',
  love_you: '🤟',
  metal: '🤘',
  point_left: '👈',
  point_right: '👉',
  point_up: '☝️',
  point_down: '👇',
  middle_finger: '🖕',
  writing_hand: '✍️',

  // Hearts
  heart: '❤️',
  red_heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  brown_heart: '🤎',
  broken_heart: '💔',
  sparkling_heart: '💖',
  heartpulse: '💗',
  heartbeat: '💓',
  two_hearts: '💕',
  revolving_hearts: '💞',

  // Symbols
  fire: '🔥',
  star: '⭐',
  sparkles: '✨',
  boom: '💥',
  zap: '⚡',
  rainbow: '🌈',
  sunny: '☀️',
  cloud: '☁️',
  snowflake: '❄️',
  droplet: '💧',
  check: '✅',
  white_check_mark: '✅',
  x: '❌',
  warning: '⚠️',
  no_entry: '🚫',
  question: '❓',
  exclamation: '❗',
  100: '💯',
  dollar: '💵',
  moneybag: '💰',
  chart: '📈',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',

  // Objects
  rocket: '🚀',
  airplane: '✈️',
  car: '🚗',
  bike: '🚲',
  ship: '🚢',
  trophy: '🏆',
  medal: '🏅',
  gift: '🎁',
  balloon: '🎈',
  tada: '🎉',
  party_popper: '🎉',
  confetti_ball: '🎊',
  bell: '🔔',
  key: '🔑',
  lock: '🔒',
  unlock: '🔓',
  bulb: '💡',
  mag: '🔍',
  wrench: '🔧',
  hammer: '🔨',
  gear: '⚙️',
  link: '🔗',
  paperclip: '📎',
  pushpin: '📌',
  scissors: '✂️',
  pencil: '✏️',
  memo: '📝',
  book: '📖',
  bookmark: '🔖',
  calendar: '📅',
  clock: '🕐',
  hourglass: '⏳',
  stopwatch: '⏱️',
  alarm_clock: '⏰',
  phone: '📱',
  computer: '💻',
  keyboard: '⌨️',
  email: '📧',
  envelope: '✉️',
  mailbox: '📬',
  package: '📦',
  camera: '📷',
  video_camera: '📹',
  tv: '📺',
  microphone: '🎤',
  headphones: '🎧',
  guitar: '🎸',
  musical_note: '🎵',
  notes: '🎶',

  // People
  eyes: '👀',
  eye: '👁️',
  ear: '👂',
  nose: '👃',
  tongue: '👅',
  lips: '👄',
  baby: '👶',
  boy: '👦',
  girl: '👧',
  man: '👨',
  woman: '👩',
  angel: '👼',
  ghost: '👻',
  alien: '👽',
  robot: '🤖',
  skull: '💀',
  poop: '💩',

  // Animals
  dog: '🐶',
  cat: '🐱',
  mouse: '🐭',
  hamster: '🐹',
  rabbit: '🐰',
  fox: '🦊',
  bear: '🐻',
  panda: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐮',
  pig: '🐷',
  frog: '🐸',
  monkey: '🐵',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  eagle: '🦅',
  duck: '🦆',
  owl: '🦉',
  bat: '🦇',
  wolf: '🐺',
  horse: '🐴',
  unicorn: '🦄',
  bee: '🐝',
  bug: '🐛',
  butterfly: '🦋',
  snail: '🐌',
  octopus: '🐙',
  fish: '🐟',
  dolphin: '🐬',
  whale: '🐳',
  shark: '🦈',
  crab: '🦀',
  turtle: '🐢',
  snake: '🐍',
  dragon: '🐉',
  dinosaur: '🦕',

  // Food
  apple: '🍎',
  banana: '🍌',
  grapes: '🍇',
  strawberry: '🍓',
  watermelon: '🍉',
  lemon: '🍋',
  orange: '🍊',
  peach: '🍑',
  cherry: '🍒',
  avocado: '🥑',
  eggplant: '🍆',
  potato: '🥔',
  carrot: '🥕',
  corn: '🌽',
  pepper: '🌶️',
  broccoli: '🥦',
  pizza: '🍕',
  burger: '🍔',
  fries: '🍟',
  hotdog: '🌭',
  taco: '🌮',
  burrito: '🌯',
  sushi: '🍣',
  ramen: '🍜',
  spaghetti: '🍝',
  bread: '🍞',
  croissant: '🥐',
  cake: '🎂',
  cupcake: '🧁',
  pie: '🥧',
  cookie: '🍪',
  chocolate: '🍫',
  candy: '🍬',
  lollipop: '🍭',
  icecream: '🍦',
  donut: '🍩',
  coffee: '☕',
  tea: '🍵',
  beer: '🍺',
  beers: '🍻',
  wine: '🍷',
  cocktail: '🍸',
  champagne: '🍾',
};

/**
 * Common emojis for quick picker display.
 */
export const COMMON_EMOJIS = [
  '👍', '👎', '❤️', '😂', '😮', '😢', '🎉', '🔥',
  '👀', '✅', '🚀', '💯', '🙏', '👏', '😊', '🤔',
];

/**
 * Search emojis by query string.
 * Returns matching emojis with their shortcodes.
 */
export function searchEmojis(query: string, limit = 10): Array<{ shortcode: string; emoji: string }> {
  if (!query) {
    return COMMON_EMOJIS.slice(0, limit).map(emoji => {
      const shortcode = Object.entries(EMOJI_MAP).find(([, e]) => e === emoji)?.[0] || '';
      return { shortcode, emoji };
    });
  }

  const lowerQuery = query.toLowerCase();
  const results: Array<{ shortcode: string; emoji: string; score: number }> = [];

  for (const [shortcode, emoji] of Object.entries(EMOJI_MAP)) {
    if (shortcode.includes(lowerQuery)) {
      // Prefer exact matches and prefix matches
      const score = shortcode === lowerQuery ? 0 : shortcode.startsWith(lowerQuery) ? 1 : 2;
      results.push({ shortcode, emoji, score });
    }
  }

  return results
    .sort((a, b) => a.score - b.score || a.shortcode.localeCompare(b.shortcode))
    .slice(0, limit)
    .map(({ shortcode, emoji }) => ({ shortcode, emoji }));
}
